gui-apps/hyprshot: new package
gentoo/guru pull request #198
Opened 2024-06-11 08:55 UTC by ProMix0

2024-06-12 14:13 UTC, antecrescent requested changes
Thank you for the contribution!

Your commit is not OpenPGP-signed and missed the `Signed-off-by` tag.
This wikipage contains instructions on how to fix that: https://wiki.gentoo.org/wiki/Project:GURU/Information_for_Contributors#Committing

Hyprshot has optional runtime dependencies on `gui-apps/hyprpicker` and `x11-misc/xdg-user-dirs`. Please add those using the [optfeature](https://devmanual.gentoo.org/eclass-reference/optfeature.eclass/index.html) eclass.

2024-06-15 10:57 UTC, MrRoy commented on gui-apps/hyprshot/hyprshot-1.2.3.ebuild
> +# Distributed under the terms of the ISC License
This was copied verbatim from wayland-desktop overlay, where the ISC license is enforced

2024-06-15 11:50 UTC, antecrescent commented on gui-apps/hyprshot/hyprshot-1.2.3.ebuild
> +# Distributed under the terms of the ISC License
Ah, I didn't check that :+1: Thanks for letting me know.

2024-06-19 12:28 UTC, ProMix0 commented
Thanks for all the review! I had a few questions left

Should I have to send public key to email, specified [here](https://wiki.gentoo.org/wiki/Project:GURU/Information_for_Contributors#Prior_setup)? If so, I haven't @gentoo.org mail cause I'm not a developer. What should I do?

2024-06-21 11:42 UTC, antecrescent requested changes

2024-06-21 11:42 UTC, antecrescent commented on gui-apps/hyprshot/hyprshot-1.2.3.ebuild
> +
Missing license comment. It was present in the earlier revision.

e.g. `# Distributed under the terms of the GNU General Public License v2`

2024-06-21 11:42 UTC, antecrescent commented on gui-apps/hyprshot/hyprshot-1.3.0.ebuild
> +
Missing license.

2024-06-21 11:42 UTC, antecrescent commented on gui-apps/hyprshot/hyprshot-9999.ebuild
> +
Missing license.

2024-06-21 13:09 UTC, antecrescent commented
> Should I have to send public key to email, specified [here](https://wiki.gentoo.org/wiki/Project:GURU/Information_for_Contributors#Prior_setup)?

No. In all cases, you must [create an account](https://bugs.gentoo.org/createaccount.cgi) on Gentoo's Bugzilla with the same email address as the one that's listed in `metadata.xml`, before your contribution can be merged.

If you want to commit regularly, you can request access to the server so that you can push directly to the `dev` branch. To do that, you need to fulfill the requirements listed on https://wiki.gentoo.org/wiki/Project:GURU/Information_for_Contributors#Prior_setup and follow the `file an access request` link to create a new ticket with your information.

2024-06-24 20:52 UTC, antecrescent commented
LGTM. Friendly ping @MrRoy since I don't know, if regular contributors such as myself can close GitHub PRs.

2024-06-30 17:57 UTC, MrRoy commented
@antecrescent yes you can close PRs via commit tags (`Closes: <URL to PR>`) but you can also use [`app-portage/pram`](https://wiki.gentoo.org/wiki/Gentoo_git_workflow#using_pram) which automates the process

2024-07-04 11:19 UTC, closed without merging