Make the ags work
gentoo/guru pull request #212
Opened 2024-07-12 08:35 UTC by singer233

Currently after install this package the `/usr/bin/ags` is soft link to a place inside the image which will be removed after portage install and make ags unusable this change just manually create a link point to the correct location after the `src_install`

2024-07-12 13:46 UTC, antecrescent requested changes
Thanks for the contribution! Commits to (official) Gentoo ebuild repositories should adhere to [GLEP 66](https://www.gentoo.org/glep/glep-0066.html).
To do so without much headache, follow the [GURU contribution guide](https://wiki.gentoo.org/wiki/Project:GURU/Information_for_Contributors).
You don't need to request access to the server to get this commit merged, but you should consider filing an access request bug if you plan to contribute again. 

I'll merge your changes together with other improvements to this package that are sitting on my drive :^)

2024-07-12 13:46 UTC, antecrescent commented on gui-apps/aylurs-gtk-shell/aylurs-gtk-shell-1.8.2.ebuild
> +	ln -s /usr/share/com.github.Aylur.ags/com.github.Aylur.ags ${D}/usr/bin/ags
Please fix [`post_install.sh`](https://github.com/Aylur/ags/blob/bb91f7c8fdd2f51c79d3af3f2881cacbdff19f60/post_install.sh#L12) instead. Either make `/usr/bin/ags` a relative symlink or fix the absolute symlink such that `$BIN_SRC` doesn't contain `$DESTDIR`.
This is an upstream bug that should be reported.

2024-07-13 10:31 UTC, singer233 commented
Hi just update the ebuild and add a patch that will make `$BIN_SRC`  did not contain `$DESTDIR`, please review

2024-07-13 15:13 UTC, antecrescent commented
Looks good to me!
Please squash your commits and agree to our [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html) by adding a `Signed-off-by` tag. Make sure that your name on the tag line is either your real name or an established online identity. "Tim" is not enough.
You can either use [`dev-util/pkgdev`](https://wiki.gentoo.org/wiki/Pkgdev) or do it manually with `git commit -s`.

Finally, your commit message should start with `gui-apps/aylurs-gtk-shell: ...`.

2024-07-14 11:54 UTC, singer233 commented
Just committed and pushed with pkgdev. hopefully it is correct. Thanks for the guide

2024-07-14 14:50 UTC, antecrescent commented
The commit looks good, I just need you to squash them  into one, please.
e.g.
```sh
git reset --soft HEAD~2
pkgdev commit -m 'gui-apps/aylurs-gtk-shell: patch the symbol link

make the symbol link point to the right position instead of path inside
image dir'
```

2024-07-15 01:54 UTC, singer233 commented
Just pushed please review. It should be squashed into one. Thanks for the command

2024-07-15 02:27 UTC, antecrescent commented
>Just pushed please review. It should be squashed into one. Thanks for the command 
>

I noticed that you reverted the name in the `Signed-off-by` tag back to "Tim". Could you fix that and force-push your commit again, please? It has to be either your full name or an established online identity. Thanks!

2024-07-15 04:33 UTC, singer233 commented
I have changed it to my full name. please review

2024-07-15 12:40 UTC, antecrescent commented
This PR will be closed once https://github.com/gentoo/guru/commit/2f01813be7d5f8bd9a0b6685072acdbe38ba865c gets merged into `master`. Thanks you for contributing!

2024-07-15 19:27 UTC, closed without merging