mpv-plugin/open-in-mpv: new package, add 2.4.0
gentoo/guru pull request #252
Opened 2024-10-25 11:52 UTC by vitaly-zdanevich

Replacement for https://github.com/gentoo/guru/commit/17ce9413138cbd22bdff4ddb26e205f735e3bbee#diff-de89c63c4a2f61950d8337a8c2be1939190e122bba9dd4cad2c5a53a7f2814afL9

2024-10-30 23:51 UTC, vitaly-zdanevich commented
@pastalian please review

2024-10-31 14:07 UTC, pastalian commented
I don't really have any comments on this ebuild. You should get approval from guru-trusted, which I'm not a part of.

2024-10-31 14:26 UTC, stkw0 commented
Could we have a non -bin ebuild? It seems doable

2024-11-01 00:36 UTC, vitaly-zdanevich commented
Ok, but it is also good to have `-bin` as a backup, and for simplicity - so user can install it without Go compiler. I will create source-based ebuild after merging of this one - do not want to mess with git branches.

2024-11-01 00:54 UTC, stkw0 commented
About "backups", that's why we usually left at least one older version, so if a new version is broken one can switch to the older one.
As for simplicity, -bin packages complicates things. It's harder to have consistency across the system, it's harder to unbundle libraries, it's more complicated to get security updates if it builds with static libraries. 

Only when a package is arguably difficult to build from source (eg: electron programs) or there is some other justification (eg: very big build times as with libreoffice) it's reasonable to have a -bin version. I don't find any good reasons to have a binary for this, so I am not merging it.

2024-11-02 02:03 UTC, vitaly-zdanevich commented
But why Gentoo added binary mirror for all packages? https://www.gentoo.org/news/2023/12/29/Gentoo-binary.html

> To speed up working with slow hardware and for overall convenience

2024-11-02 11:17 UTC, stkw0 commented
As you quote it, for slow hardware and programs that take a lot to compile. Because adding a duplicated `-bin` ebuilds is a very poor solution, and because portage had supported binhosts for a lot of years. Traditionally, if you wanted binaries, you created your own custom binhost. Now Gentoo is kind enough to provide and maintain an official binhost for people who might want it.

Another important point is that portage will detect if the USE flags are different or there is some change between the binhost and your computer in which case it will fall back to compile the program instead of graving the binary. This keeps the coherency of your system, which is much harder to do when one installs pre-compiled binaries without any kind of checking of how those binaries were built. 

If you want binaries for arbitrary packages, create your own binhost with whatever is convenient for you. See https://wiki.gentoo.org/wiki/Binary_package_guide

2024-11-03 17:21 UTC, vitaly-zdanevich commented
ok, asked upstream about vendoring https://github.com/Baldomo/open-in-mpv/issues/37

2024-11-05 01:02 UTC, stkw0 commented
As it says in the wiki, you can also upload the tarball to Github and create a tag for each release.

2024-11-18 12:49 UTC, MrRoy commented
@vitaly-zdanevich the procedure to package the dependencies is documented here: https://wiki.gentoo.org/wiki/Writing_go_Ebuilds#Packaging_the_dependencies
You can host them on a GitHub or GitLab repository at not cost to you.

It is the packager's job to package dependencies for Gentoo, not upstream. If you will not do it, then please close this PR.

2024-12-21 22:24 UTC, vitaly-zdanevich commented
Upstream is ready, now it my turn... https://github.com/Baldomo/open-in-mpv/commit/803f94c90d2a836925cf607490c10f45901bb045

2025-01-31 09:45 UTC, vitaly-zdanevich commented
@MrRoy please review.

2025-02-22 00:17 UTC, StefanCristian requested changes
Other than the package should be moved to `media-video` instead of `mpv-plugin`, it compiled nicely.

@vitaly-zdanevich Please provide some steps to reproduce / get it configured to use.

2025-02-22 00:17 UTC, StefanCristian commented on mpv-plugin/open-in-mpv/open-in-mpv-2.4.1.ebuild
> +inherit go-module desktop xdg-utils
@vitaly-zdanevich You can use simply `xdg`, and remove the pkg_postinst() and postrm()

2025-02-22 00:17 UTC, StefanCristian commented on mpv-plugin/open-in-mpv/open-in-mpv-2.4.1.ebuild
> +	media-video/mpv
@vitaly-zdanevich you can also move this package to media-video category, since there is no mpv-plugin category.

2025-02-22 00:17 UTC, StefanCristian commented on mpv-plugin/open-in-mpv/open-in-mpv-2.4.1.ebuild
> +	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 ego build -ldflags="-s -w -X main.Version=${PV}" -o ${PN} ./cmd/open-in-mpv/
This is optional: if it can be compiled on other architectures, like aarch/arm64, you can condition amd64 here. Otherwise, it's fine.

2025-02-22 03:10 UTC, vitaly-zdanevich commented on mpv-plugin/open-in-mpv/open-in-mpv-2.4.1.ebuild
> +	media-video/mpv
> there is no mpv-plugin category

https://github.com/gentoo/guru/tree/master/mpv-plugin

2025-02-22 03:46 UTC, vitaly-zdanevich commented
> Please provide some steps to reproduce / get it configured to use.

1) Emerge this
2) Install https://addons.mozilla.org/en-US/firefox/addon/iina-open-in-mpv
3) Go to, for example, https://www.youtube.com/watch?v=UHbre6vkc1w
4) Click extension button in Firefox, or in Firefox context menu
5) Expected: opened mpv playing the video from YouTube

2025-02-22 04:10 UTC, vitaly-zdanevich commented on mpv-plugin/open-in-mpv/open-in-mpv-2.4.1.ebuild
> +	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 ego build -ldflags="-s -w -X main.Version=${PV}" -o ${PN} ./cmd/open-in-mpv/
I believe that it should work 99%, but in the perfect world scenario somebody needs to check on real hardware...

2025-02-22 06:53 UTC, vitaly-zdanevich commented
@StefanCristian done.

2025-02-22 14:48 UTC, StefanCristian commented on mpv-plugin/open-in-mpv/open-in-mpv-2.4.1.ebuild
> +	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 ego build -ldflags="-s -w -X main.Version=${PV}" -o ${PN} ./cmd/open-in-mpv/
> I believe that it should work 99%, but in the perfect world scenario somebody needs to check on real hardware...

It's ok, you can keep it like this, and if someone manifests interest, they will ask for additional architectures.

2025-02-22 14:48 UTC, StefanCristian commented
> > Please provide some steps to reproduce / get it configured to use.
> 
> 1. Emerge this
> 2. Install https://addons.mozilla.org/en-US/firefox/addon/iina-open-in-mpv
> 3. Go to, for example, https://www.youtube.com/watch?v=UHbre6vkc1w
> 4. Click extension button in Firefox, or in Firefox context menu
> 5. Expected: opened mpv playing the video from YouTube

Perfect. I will test today or tomorrow when I have a bit of time.

2025-02-22 14:50 UTC, StefanCristian commented on mpv-plugin/open-in-mpv/open-in-mpv-2.4.1.ebuild
> +	media-video/mpv
> > there is no mpv-plugin category
> 
> https://github.com/gentoo/guru/tree/master/mpv-plugin

Oh, I judged based on standard categories from main gentoo repository. I think it's fine to keep it like this if any maintainers agree. All cool.

2025-02-22 22:27 UTC, StefanCristian commented on mpv-plugin/open-in-mpv/open-in-mpv-2.4.1.ebuild
> +	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 ego build -ldflags="-s -w -X main.Version=${PV}" -o ${PN} ./cmd/open-in-mpv/
> I don't understand why it is hardcoded to Linux and amd64, this should be set automatically by go eclass. If there is no specific reason, I think it should be removed.

I was thinking more from the conditional pov like a IF it's amd64?, but GOOS and GOARCH can indeed go away from the arguments if no conditionals are specified.
I don't think there is a specific reason to keep them, go does build based on arch detection, so it's perfectly fine without them :+1: 
CC @vitaly-zdanevich 

I'll check tomorrow as well, to maje sure everything is fine on my side as well.

2025-02-23 15:48 UTC, StefanCristian commented
> > Please provide some steps to reproduce / get it configured to use.
> 
> 1. Emerge this
> 2. Install https://addons.mozilla.org/en-US/firefox/addon/iina-open-in-mpv
> 3. Go to, for example, https://www.youtube.com/watch?v=UHbre6vkc1w
> 4. Click extension button in Firefox, or in Firefox context menu
> 5. Expected: opened mpv playing the video from YouTube

@vitaly-zdanevich Does it need some special config? I tried opening a random youtube, installed extension as per step (2) in your, went to a random video like in (3), clicked the extension button -> got this:

![image](https://github.com/user-attachments/assets/897d3570-fa2f-4842-989d-2362a196b570)

... and does nothing after.
MPV itself works fine, I tested it on something else.

But I might have a hunch, and that will surely help your ebuild, meaning: does my mpv need to be compiled with something extra from this list?

`[ebuild   R    ] media-video/mpv-0.39.0:0/2::gentoo  USE="X alsa cdda cli drm dvd egl iconv jpeg lcms libmpv lua openal opengl pipewire uchardet vulkan wayland xv zlib (-aqua) -archive -bluray (-coreaudio) -debug -dvb -gamepad -jack -javascript -libcaca -nvenc -pulseaudio -rubberband -sdl (-selinux) -sixel -sndio -soc -test -tools -vaapi -vdpau -zimg" LUA_SINGLE_TARGET="(luajit) (-lua5-1)" PYTHON_SINGLE_TARGET="python3_12 -python3_10 -python3_11 -python3_13" 0 KiB`

2025-02-24 13:17 UTC, StefanCristian commented
> @StefanCristian is such command open video for you?
> 
> `mpv "https://www.youtube.com/watch?v=UHbre6vkc1w"`

mpv "https://youtu.be/5l5LGrbH-8k?si=2gyJiC57Dag_pa84"
[ytdl_hook] Subprocess failed: init
[ytdl_hook] Subprocess failed: init
[ytdl_hook] Subprocess failed: init
[ytdl_hook] 
[ytdl_hook] youtube-dl failed: not found or not enough permissions
Failed to recognize file format.
Exiting... (Errors when loading file)

Alright, found the right answer.
I manually emerge `yt-dlp`, and everything worked via Firefox as well via extension, as well as manually in terminal.

So what I recommend is adding either a `einfo` or a `optfeature` to this ebuild, so that when someone installs this ebuild, they would also install be informed to install `yt-dlp` (which is the fork well supported in gentoo packages https://packages.gentoo.org/packages/net-misc/yt-dlp).

And that's about it.
Make sure it compiles without GOOS and GOARCH, and it's a good to go. I'll test as well.

2025-02-24 23:50 UTC, vitaly-zdanevich commented
I added `yt-dlp` dep a few days ago.

2025-02-24 23:53 UTC, vitaly-zdanevich commented
> Make sure it compiles without GOOS and GOARCH

done.

2025-02-24 23:54 UTC, vitaly-zdanevich commented on mpv-plugin/open-in-mpv/open-in-mpv-2.4.1.ebuild
> +	net-misc/yt-dlp
@StefanCristian this dep is already here, looks like I added it after you emerge.

2025-02-25 00:16 UTC, StefanCristian commented
Well, looks good to me. @stkw0 if you want to add something else.

2025-02-25 00:21 UTC, stkw0 commented
The ebuilds looks fine to me. Before merging the commits should be rebased to have 1 commit instead of 7

2025-02-25 12:45 UTC, StefanCristian commented
> The ebuilds looks fine to me. Before merging the commits should be rebased to have 1 commit instead of 7

@vitaly-zdanevich ^ this is in order to be able for @stkw0 to pull one single commit from your side, and push it into CGIT gentoo-guru. Also for aesthetic reasons, but mainly the ease of pulling commit, since Gentoo-guru on Github is just a mirror. :+1:

2025-02-26 01:53 UTC, vitaly-zdanevich commented
Rebased into one commit.

2025-02-26 15:45 UTC, closed without merging